name: JS Docs Test

on:
  push:
    branches:
      - jsdoc-automation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src/scripts
          recurse: true
          output_dir: ./out
          config_file: conf.json
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{  secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./out
